<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'SYMFONY_DOTENV_PATH' => './.env',
  'DB_ROOT_PASSWORD' => 'root',
  'DB_USER_PASSWORD' => 'user',
  'DB_USER_NAME' => 'user',
  'DB_HOST' => 'db',
  'DB_DATABASE_NAME' => 'trade',
  'APP_SECRET' => '9b29c2ec91ffe557768d754ad8a4f2d7',
  'DATABASE_URL' => 'mysql://root:root@db:3306/trade?serverVersion=11.6.2-MariaDB&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
