api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: ['application/json']
    defaults:
        stateless: true
        route_prefix: v1
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
